baseurl = "/"
title = "Public Money, Public Code"
theme = "hugo-creative-theme"
DefaultContentLanguage = "en"

# Static strings shared by all languages â€“ these are not to be translated!
[params.static]
  url         = "https://publiccode.asia"
  slogan_1    = "Public Money"
  slogan_2    = "Public Code"
  promoLink   = "https://github.com/fossasia/fossasia-artwork/tree/master/PublicCode"
  language    = "Language"

[params.static.meta]
  author        = "FOSSASIA"
  previewImage  = "img/share-graphics/why.png"
  fbPageID      = "fossasia"
  twitterUser   = "@fossasia"

# === TRANSLATIONS ===
[Languages]
