# == NEDERLANDS ==

# General strings
[Languages.nl]
  # languageCode  = "en"
  # languageName  = "English"
  # description   = "Public Money, Public Code - A campaign for releasing publicly financed software as Free Software"
  # fsdefinition  = "Free Software gives everybody the rights to use, study, share and improve software. These rights help support other fundamental freedoms like freedom of speech, press and privacy."
  languageCode  = "nl"  # 2-letter code of language (ISO 639-1)
  languageName  = "Nederlands"  # verbose name of language (e.g. "Français" or "Русский")
  description   = "Public Geld, Publieke Code - Een campagne om publiek gefinancieerde software uit te brengen als Vrije Software"
  fsdefinition  = "Vrije Software geeft iedereen het recht om software te gebruiken, te begrijpen, aan te passen en te delen. Deze rechten helpen het ondersteunen van andere fundamentele vrijheden zoals de vrijheid van meningsuiting, pers en privacy."


# Navigation
[Languages.nl.navigation]
[Languages.nl.navigation.links]
  # start     = "Start"
  # about     = "About"
  # arguments = "Reasons"
  # action    = "Take Action"
  # spread    = "Spread the Word"
  start     = "Begin"
  about     = "Over"
  arguments = "Stellingen"
  action    = "Onderneem Actie"
  spread    = "Deel"


# Start banner
[Languages.nl.start]
  # subtitle1   = "Why is software created using taxpayers' money not released as Free Software?"
  # subtitle2   = "We want legislation requiring that publicly financed software developed for the public sector be made publicly available under a [Free and Open Source Software](https://fsfe.org/about/mission.html 'Free Software gives everybody the rights to use, study, share and improve software. These rights help support other fundamental freedoms like freedom of speech, press and privacy.') licence. If it is public money, it should be public code as well."
  # subtitle3   = "**Code paid by the people should be available to the people!**" 
  subtitle1  = "Waarom is software die geschreven is met belastinggeld niet beschikbaar als Vrije Software?"
  subtitle2  = "Wij willen wetgeving die het nodig maakt dat publiek gefinancieerde software geschreven voor de publieke sector beschikbaar gemaakt wordt onder een [Vrije en Open Bronlicentie](https://fsfe.org/about/mission.nl.html 'Vrije Software geeft iedereen het recht om software te gebruiken, te begrijpen, aan te passen en te delen. Deze rechten helpen het ondersteunen van andere fundamentele vrijheden zoals de vrijheid van meningsuiting, pers en privacy.').  Als het publiek geld is, dan moet het ook publieke code zijn."
  subtitle3  = "**Code die betaald is door iedereen moet beschikbaar zijn voor iedereen!**"


# About section
[Languages.nl.about]
  # headline    = "Sound complicated? It's not. It's super easy!"
  # buttonText  = "More advantages"
  headline    = "Klinkt ingewikkeld? Nee, het is heel simpel!"
  buttonText  = "Meer voordelen"


# Arguments section
[Languages.nl.arguments]
  # headline    = "Reasons for Public Code"
  # followup    = "Do you believe that Free Software should be the default option for publicly financed software? **Let's convince your political representatives!**"
  # buttonText  = "Sign the Open Letter"
  headline    = "Redenen voor Publieke Code"
  followup    = "Gelooft u dat Vrije Software de standaardoptie zou moeten zijn voor publiek gefinancieerde software?  **Laten we onze politieke vertegenwoordigers overtuigen!**"
  buttonText  = "Onderteken de Open Brief"
[[Languages.nl.arguments.list]]
  # icon        = "fa-eur"
  # title       = "Tax savings"
  # description = "Similar applications don't have to be programmed from scratch every time."
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Besparen op belastingen"
  description = "Soortgelijke toepassingen hoeven niet opnieuw van de grond af ontwikkeld te worden."
[[Languages.nl.arguments.list]]
  # icon        = "fa-handshake-o"
  # title       = "Collaboration"
  # description = "Efforts on major projects can share expertise and costs."  
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "Samenwerking"
  description = "Grote projecten kunnen samenwerken om expertise en kosten te delen."
[[Languages.nl.arguments.list]]
  # icon        = "fa-users"
  # title       = "Serving the public"
  # description = "Applications paid by the public should be available for everyone."
  icon        = "fa-users"  # <-- do not translate this
  title       = "Algemeen belang"
  description = "Programma's betaald door het publiek zouden voor iedereen beschikbaar moeten zijn."
[[Languages.nl.arguments.list]]
  # icon        = "fa-lightbulb-o"
  # title       = "Fostering innovation"
  # description = "With transparent processes, others don't have to reinvent the wheel."
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Innovatie bevorderen"
  description = "Met transparante processen hoeft het wiel niet opnieuw uitgevonden te worden."


# Action section
[Languages.nl.action]
  # headline      = "Tell Your Representatives!"
  # intro         = "In our [**open letter**](openletter/) we demand:" 
  # demand        = "“Implement legislation requiring that publicly financed software developed for the public sector be made publicly available under a [Free and Open Source Software](https://fsfe.org/about/mission.html 'Free Software gives everybody the rights to use, study, share and improve software. These rights help support other fundamental freedoms like freedom of speech, press and privacy.') licence.”"
  # description   = "**$ORGS** organisations and **$INDS** individuals already support this call for action by signing our [open letter](openletter/). You can help us make a much bigger impact by signing it, too! We will hand over all signatures to representatives all over Europe that are debating software freedom in public administration."
  headline      = "Vertel uw vertegenwoordigers!"
  intro         = "In onze [**open brief**](openletter/) eisen we:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“Creëer wetgeving die vereist dat publiek gefinancierde software ontwikkeld voor de publieke sector openbaar beschikbaar gesteld moet worden onder een Vrije en Open Bron Softwarelicentie.”"
  description   = "**$ORGS** organisaties en **$INDS** individuen hebben onze oproep al gesteund door de [Open Brief](openletter/) te ondertekenen.  Help ons om een verschil te maken door het ook te ondertekenen!  Wij zullen alle handtekeningen overhandigen aan vertegenwoordigers in heel Europa die debatteren over softwarevrijheid in overheden."

[Languages.nl.action.box]
  # text      = "Already **$INDS SIGNATURES** – sign the open letter now!"
  text      = "Al **$INDS HANDTEKENINGEN** – Onderteken de Open Brief nu!"

[Languages.nl.action.form]
  # name      = "Name (required)"
  # email     = "Email (required)"
  # country   = "Your Country"
  # zip       = "Zip Code"
  # comment   = "Your comment (max. 140 characters)"
  # permPriv  = "I have read and accepted the [privacy statement](privacy/)"
  # permNews  = "I want to stay informed about the future of this campaign"
  # permPub   = "I want my signature to appear in the [list of signatures](openletter/all-signatures)"
  # submit    = "Sign Now!"
  name      = "Naam (verplicht)"
  email     = "E-mail (verplicht)"
  country   = "Uw land"
  zip       = "Postcode"
  comment   = "Uw commentaar (max. 140 karakters)"
  permPriv  = "Ik heb het [privacybeleid](privacy/) gelezen en geaccepteerd"
  permNews  = "Ik wil graag op de hoogte blijven van deze campagne"
  permPub   = "Ik wil graag dat mijn handtekening op de [lijst van handtekeningen](openletter/all-signatures) verschijnt"
  submit    = "Onderteken nu!"


# Organisations section
[Languages.nl.organisations]
  # headline  = "Supporting Organisations"
  # text      = "The following organisations support our [open letter](openletter/). If your organisation is also interested in joining the call for Public Code, please [contact us](mailto:contact@fsfe.org)."
  headline  = "Ondersteunende organisaties"
  text      = "De volgende organisaties steunen onze [Open Brief](openletter/). Als uw organisatie ook geïnteresseerd is om mee te doen aan de eis voor Publieke Code, neem dan [contact](mailto:contact@fsfe.org) met ons op."


# Spread the word section
[Languages.nl.spread]
  # headline          = "Spread the word!"
  # promoText         = "Order the latest stickers and flyers from FSFE"
  # promoButtonText   = "Get promo material"
  # shareText         = "Tell your friends and followers about Public Code:"
  # defaultSocialText = "If it is public money, it should be public code as well. I support this call for more public code under a Free Software license: "
  headline          = "Vertel het verder!"
  promoText         = "Bestel de nieuwste stickers en flyers van de FSFE"
  promoButtonText   = "Bestel promotiemateriaal"
  shareText         = "Vertel uw vrienden en volgers over Publieke Code:"
  defaultSocialText = "Als het publiek geld is, dan moet het ook publieke code zijn! Ik steun de eis voor meer publieke code onder een Vrije Softwarelicentie: "


# Legal Section
[Languages.nl.legal]
  # by            = "This is a campaign by Free Software Foundation Europe"
  # imprint       = "Imprint"
  # privacy       = "Privacy"
  # transparency  = "Transparency"
  # contribute1   = "The code of this website is Free Software." 
  # contribute2   = "You're welcome to contribute!"
  # license       = "This work is licensed under a [Creative Commons BY-SA 4.0 License](http://creativecommons.org/licenses/by-sa/4.0/)."
  by            = "Dit is een compagne door Free Software Foundation Europe"
  imprint       = "Imprint"  # TODO
  privacy       = "Privacy"
  transparency  = "Openheid"
  contribute1   = "De code van deze website is Vrije Software."
  contribute2   = "U bent van harte welkom om bij te dragen!"
  license       = "Dit werk valt onder een [Creative Commons BY-SA 4.0 Licentie](http://creativecommons.org/licenses/by-sa/4.0/deed.nl)."


# Language selection
[Languages.nl.language]
  # description = "Read this page in another language"
  description = "Lees deze pagina in een andere taal"


# 404 Error Page
[Languages.nl.error]
  # headline    = "Error 404 - Page not found"
  # description = "The page you're looking for does not exist."
  # button      = "Back to start page"
  headline    = "Error 404 - Pagina niet gevonden"
  description = "De pagina die u zoekt bestaat niet."
  button      = "Terug naar de startpagina"


# Specific sub-pages
[Languages.nl.subpage]
[Languages.nl.subpage.signatures]
  # headline      = "Individual Open Letter Signatures"
  # description   = "Below are the signatures of the signees who agreed to have their names made public. Be the next one!"
  # allSignatures = "See [all public signatures](all-signatures/)."
  # tableName     = "Name"
  # tableCountry  = "Country"
  # tableComment  = "Comment"
  headline      = "Individuele handtekeningen voor de Open Brief"
  description   = "Beneden vindt u de handtekening van de mensen die toestemming gegeven hebben om hun namen publiekelijk te tonen.  Word de volgende!"
  allSignatures = "Bekijk [alle openbare handtekeningen](all-signatures/)."
  tableName     = "Naam"
  tableCountry  = "Land"
  tableComment  = "Commentaar"
