# == ESPERANTO ==

# General strings
[Languages.eo]
  languageCode  = "eo"
  languageName  = "Esperanto"
  description   = "Publika mono, publika kodo – Kampanjo por liberigi publike financitan programaron"
  fsdefinition  = "Libera programaro rajtigas ĉiujn uzi, studi, kunhavigi kaj plibonigi programaron. Tiu ĉi rajto helpas subteni aliajn fundamentajn liberecojn kiel liberecojn de parolo, preso kaj privateco."


# Navigation
[Languages.eo.navigation]
[Languages.eo.navigation.links]
  start     = "Komenco"
  about     = "Pri"
  arguments = "Kialoj"
  action    = "Agu"
  spread    = "Diskonigu"


# Start banner
[Languages.eo.start]
  subtitle1   = "Kial oni ne eldonas programaron kreitan per mono de impostpagantoj kiel liberan?"
  subtitle2   = "Ni volas leĝaron postulantan, ke publike financita programaro evoluigita por publika sektoro publike eldoniĝu sub [libera kaj malfermitkoda programa](https://fsfe.org/about/mission.html 'Libera programaro rajtigas ĉiujn uzi, studi, kunhavigi kaj plibonigi programaron. Tiu ĉi rajto helpas subteni aliajn fundamentajn liberecojn kiel liberecojn de parolo, preso kaj privateco.') permesilo. Teme pri publika mono, ankaŭ temu pri publika kodo!"
  subtitle3   = "**Kodo pagita de la popolo estu disponebla al la popolo!**"


# About section
[Languages.eo.about]
  headline    = "Ĉu sonas komplike? Tute ne. Estas tre facile!"
  buttonText  = "Pli da avantaĝoj"


# Arguments section
[Languages.eo.arguments]
  headline    = "Kialoj por publika kodo"
  followup    = "Ĉu vi opinias, ke libera programaro estu la norma agordo por publike financita programaro?  **Ni konvinku viajn politikajn deputitojn!**"
  buttonText  = "Subskribu la publikan leteron"
[[Languages.eo.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Imposta ŝparado"
  description = "Similaj aplikaĵoj ne devas esti programitaj de nulo ĉiufoje."
[[Languages.eo.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "Kunlaborado"
  description = "Penoj de grandaj projektoj povas kunhavi kompetentecojn kaj kostojn."
[[Languages.eo.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Servado al la publiko"
  description = "Aplikaĵoj pagitaj de la publiko estu disponeblaj al ĉiuj."
[[Languages.eo.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Nutrado de novigado"
  description = "Kun procedoj travideblaj, aliuloj ne devas reinventi la radon."


# Action section
[Languages.eo.action]
  headline      = "Diru all viaj deputitoj!"
  intro         = "En nia [**publika letero**](openletter/) ni postulas:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "«Efektivigu leĝaron postulantan, ke publike financita programaro evoluigita por publika sektoro devu publike eldoniĝi sub [libera kaj malfermitkoda programa](https://fsfe.org/freesoftware/basics/summary.html 'Libera programaro rajtigas ĉiujn uzi, studi, kunhavigi kaj plibonigi programaron. Ĉi tiu rajto helpas subteni aliajn fundamentajn liberecojn kiel liberecojn de parolo, preso kaj privateco.') permesilo.»"
  description   = "**$ORGS** organizaĵoj kaj **$INDS** individuoj jam subtenas ĉi tiun alvokon al ago per subskribado de nia [publika letero](openletter/). Ankaŭ vi povas helpi al ni fari pli grandan efekton! Ni donos ĉiujn subskribojn al la deputitoj ĉie en Eŭropo, kiuj pridiskutas programan liberecon en publika administrado."

[Languages.eo.action.box]
  text      = "Jam **$INDS SUBSKRIBOJ** – subskribu la publikan leteron nun!"

[Languages.eo.action.form]
  name      = "Nomo (necesa)"
  email     = "Retpoŝt-adreso (necesa)"
  country   = "Via lando"
  zip       = "Poŝta kodo"
  comment   = "Via komento (pleje 140 signoj)"
  permPriv  = "Mi legis kaj konsentis la [privateco-politikon](privacy/)"
  permNews  = "Mi volas esti informata pri ĉi tiu kampanjo estonte"
  permPub   = "Mi volas aperigi mian subskrisbon en la [listo de subskriboj](openletter/all-signatures)"
  submit    = "Subskribi nun!"


# Organisations section
[Languages.eo.organisations]
  headline  = "Subtenantaj organizaĵoj"
  text      = "La jenaj organizaĵoj subtenas nian [publikan leteron](openletter/). Se ankaŭ via organizaĵo interesiĝas pri aliĝo al la voko por publika kodo, bonvolu [nin kontakti](mailto:contact@fsfe.org)."


# Spread the word section
[Languages.eo.spread]
  headline          = "Diskonigu la kampanjon!"
  promoText         = "Mendu la plej novajn gluetikedojn kaj broŝurojn de FSFE"
  promoButtonText   = "Akiru varbilojn"
  shareText         = "Sciigu viajn amikojn kaj abonantojn pri publika kodo:"
  defaultSocialText = "Teme pri publika mono, temu pri publika kodo. Mi subtenas ĉi tiun vokon por pli da publika kodo sub liberaj permesiloj:"


# Legal Section
[Languages.eo.legal]
  by            = "Ĉi tio estas kampanjo de Free Software Foundation Europe"
  imprint       = "Organizaĵo"
  privacy       = "Privateco-politiko"
  transparency  = "Travidebleco"
  contribute1   = "Kodo de tiu ĉi retejo estas libera programaro." 
  contribute2   = "Ni bonvenigas kontribuojn!"
  license       = "Tiu ĉi verko subas la permesilon [Creative Commons BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/deed.eo)."


# Language selection
[Languages.eo.language]
  description = "Legu ĉi tiun paĝon en alia lingvo"


# 404 Error Page
[Languages.eo.error]
  headline    = "Error 404 - Paĝo ne trovita"
  description = "La paĝo, kiun vi serĉas, ne ekzistas."
  button      = "Reen al la ĉefpaĝo"


# Specific sub-pages
[Languages.eo.subpage]
[Languages.eo.subpage.signatures]
  headline      = "Individuaj subskriboj de la publika letero"
  description   = "Sube estas subskriboj de la subskribintoj, kiuj konsentis publikigon de siaj nomoj. Fariĝu unu el tiuj!"
  allSignatures = "Rigardu [ĉiujn publikajn subskribojn](all-signatures/)."
  tableName     = "Nomo"
  tableCountry  = "Lando"
  tableComment  = "Komento"
