# == BENGALI ==

## General strings
[Languages.bn]
  languageCode  = "bn"  # 2-letter code of language (ISO 639-1)
  languageName  = "বাঙালি"  # verbose name of language (e.g. "Français" or "Русский")
  description   = "পাবলিক মানি, সার্বজনীন কোড - মুক্ত এবং ওপেন সোর্স সফটওয়্যার হিসাবে জনসাধারণের অর্থায়ত্ত সফটওয়্যারটি প্রকাশের জন্য একটি ফাউসাসিয়া প্রচারাভিযান"
  fsdefinition  = "ফ্রি এবং ওপেন সোর্স সফটওয়্যার আপনাকে সফটওয়্যার ব্যবহার, গবেষণা, শেয়ার এবং উন্নত করার অধিকার দেয়।"


# Navigation
[Languages.bn.navigation]
[Languages.bn.navigation.links]
  start     = "শুরু"
  about     = "সম্পর্কিত"
  arguments = "কারণ"
  action    = "পদক্ষেপ গ্রহণ করুন"
  spread    = "শব্দটি ছড়িয়ে দিন"

# Start banner
[Languages.bn.start]
  subtitle1   = "ফ্রি এবং ওপেন সোর্স সফটওয়্যার হিসাবে মুক্তি না করায় করদাতার অর্থ ব্যবহার করে সফ্টওয়্যার তৈরি করা কেন?"
  subtitle2   = "আমরা চাই যে আইনটি পাবলিক সেক্টরের জন্য উন্মুক্তভাবে অর্থসংস্থান করা সফ্টওয়্যারটি [ফ্রি ও ওপেন সোর্স সফটওয়্যার](https://en.wikipedia.org/wiki/Free_and_open-source_software) লাইসেন্সের অধীনে সার্বজনিকভাবে উপলব্ধ করা প্রয়োজন। যদি এটি জনসাধারণের অর্থ হয়, তবে এটি অবশ্যই সার্বজনীন কোড হওয়া উচিত। [সারা পৃথিবী জুড়ে](https://publiccode.eu), আমরা জনসাধারণের দ্বারা পরিশোধিত কোডটি প্রকাশের জন্য কল করার উদ্যোগ গ্রহণ করছি।"
  subtitle3   = "**জনগণের কাছ থেকে দেওয়া কোড জনগণের কাছে পাওয়া উচিত!**"

# About section
[Languages.bn.about]
  headline    = "জটিল বলে মনে হয়? এটা না এটা সুপার সহজ!"
  buttonText  = "আরও সুবিধা"

# Arguments section
[Languages.bn.arguments]
  headline    = "পাবলিক কোড জন্য কারণ"
  followup    = "আপনি কি বিশ্বাস করেন যে মুক্ত এবং ওপেন সোর্স সফ্টওয়্যার সর্বজনীন অর্থসংস্থান সফ্টওয়্যারের জন্য ডিফল্ট বিকল্প হওয়া উচিত? **আপনার রাজনৈতিক প্রতিনিধিদের সন্তুষ্ট করা যাক!**"
  buttonText  = "ওপেন ইনিশিয়েটিভ সাইন ইন করুন"
[[Languages.bn.arguments.list]]
  icon        = "fa-usd"  # <-- do not translate this
  title       = "ট্যাক্স সঞ্চয়"
  description = "অনুরূপ অ্যাপ্লিকেশন প্রত্যেক সময় স্ক্র্যাচ থেকে প্রোগ্রাম করা হবে না।"
[[Languages.bn.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "সহযোগিতা"
  description = "প্রধান প্রকল্পগুলির প্রচেষ্টাগুলি দক্ষতা এবং খরচগুলি ভাগ করতে পারে।"
[[Languages.bn.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "জনসাধারণের সেবা"
  description = "জনসাধারণের দ্বারা প্রদত্ত অ্যাপ্লিকেশনগুলি প্রত্যেকের জন্য উপলব্ধ হওয়া উচিত।"
[[Languages.bn.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "উত্সাহ উদ্ভাবন"
  description = "স্বচ্ছ প্রক্রিয়াগুলির সাথে, অন্যরা চাকা পুনর্বিন্যাস করতে হবে না।"

# Action section
[Languages.bn.action]
  headline      = "আপনার প্রতিনিধিদের বলুন!"
  intro         = "আমাদের [**খোলা উদ্যোগ**](openinitiative/) আমরা দাবি করি:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“পাবলিক সেক্টরের জন্য উন্মুক্ত জনসাধারণের অর্থায়ত্ত সফ্টওয়্যারটি [ফ্রি ও ওপেন সোর্স সফটওয়্যার](https://en.wikipedia.org/wiki/Free_and_open-source_software) লাইসেন্সের অধীনে সার্বজনিকভাবে উপলব্ধ করা প্রয়োজন এমন আইনগুলি বাস্তবায়ন করা।”"
  description   = "**$ORGS** টি সংগঠন এবং **$INDS** জন ব্যক্তি ইতোমধ্যে আমাদের [উন্মুক্ত উদ্যোগ](openinitiative/). স্বাক্ষর দ্বারা কর্মের জন্য এই কলটি সমর্থন করেছেন। আপনিও এটিতেও সাইন করে একটি বড় প্রভাব ফেলতে সহায়তা করতে পারেন! আমরা সব স্বাক্ষরকারীর তালিকাভুক্ত করবো এবং এশিয়ার সমস্ত প্রতিনিধিদের হাতে এটি হস্তান্তর করব যা জনসাধারণের প্রশাসনের সফ্টওয়্যার নীতিগুলি বিতর্ক করে।"

[Languages.bn.action.box]
  text      = "ইতিমধ্যে **$INDS SIGNATURES** - এখন খোলা উদ্যোগ সই!"

[Languages.bn.action.form]
  name          = "নাম (প্রয়োজন)"
  email         = "ই - মেইল (আবশ্যক)"
  country       = "তোমার দেশ"
  region        = "অঞ্চল/শহর"
  organization  = "সংগঠন"
  comment       = "আপনার মন্তব্য (সর্বাধিক 140 অক্ষর)"
  permPriv      = "আমি [গোপনীয়তা বিবৃতি](privacy/) পড়েছি এবং স্বীকার করেছি"
  permNews      = "আমি এই প্রচারাভিযানের ভবিষ্যৎ সম্পর্কে অবগত থাকব"
  permPub       = "আমি আমার স্বাক্ষরকে [স্বাক্ষর তালিকা](openinitiative/all-signatures)"
  submit        = "এখনই সাইন করুন!"

# Organisations section
[Languages.bn.organisations]
  headline  = "সাপোর্টিং সংস্থা"
  text      = "নিম্নলিখিত সংস্থাগুলি আমাদের [উন্মুক্ত উদ্যোগ](openinitiative/). সমর্থন করে। যদি আপনার সংস্থা জনসাধারণের কোডের কলটিতে যোগদান করতে আগ্রহী তবে দয়া করে [আমাদের সাথে](mailto:publiccode@fossasia.org)."


# Spread the word section
[Languages.bn.spread]
  headline          = "শব্দ ছড়িয়ে!"
  promoText         = "FOSSASIA থেকে স্টিকার এবং প্রচার পত্র পান"
  promoButtonText   = "তথ্য উপাদান ডাউনলোড করুন"
  shareText         = "পাবলিক কোড সম্পর্কে আপনার বন্ধু এবং অনুগামীদের বলুন:"
  defaultSocialText = "যদি এটি জনসাধারণের অর্থ হয়, তবে এটি অবশ্যই সার্বজনীন কোড হওয়া উচিত। আমি একটি ফ্রি সফটওয়্যার লাইসেন্সের অধীনে আরও পাবলিক কোডের জন্য এই কলটি সমর্থন করি:"

# Legal Section
[Languages.bn.legal]
  by            = "এই FOSSASIA দ্বারা একটি প্রচারণা"
  imprint       = "অঙ্কিত করা"
  privacy       = "গোপনীয়তা"
  transparency  = "স্বচ্ছতা"
  contribute1   = "এই ওয়েবসাইটের কোডটি ফ্রি এবং ওপেন সোর্স সফটওয়্যার হিসাবে লাইসেন্স করা হয়েছে।"
  contribute2   = "আপনি অবদান স্বাগত জানাই!"
  license       = "এই [ক্রিয়েটিভ ক্রিয়েটিভ কমন্স BY-SA 4.0 লাইসেন্সের](http://creativecommons.org/licenses/by-sa/4.0/) অধীনে তার [অবদানকারীদের](https://github.com/fossasia/publiccode.asia/contributors) দ্বারা লাইসেন্স করা হয়"

# Language selection
[Languages.bn.language]
  description = "অন্য ভাষায় এই পৃষ্ঠাটি পড়ুন"


# 404 Error Page
[Languages.bn.error]
  headline    = "ত্রুটি 404 - পৃষ্ঠাটি পাওয়া যায়নি"
  description = "আপনি খুঁজছেন পাতাটি অস্তিত্ব নেই"
  button      = "পৃষ্ঠার শুরুতে ফিরে যান"


# Specific sub-pages
[Languages.bn.subpage]
[Languages.bn.subpage.signatures]
  headline      = "স্বতন্ত্র উদ্যোগের স্বাক্ষর"
  description   = "নীচে স্বাক্ষরকারীর স্বাক্ষর রয়েছে যারা তাদের নাম প্রকাশের জন্য সম্মত হন। পরের এক হতে হবে!"
  allSignatures = "[সকল পাবলিক স্বাক্ষর](all-signatures/) দেখুন."
  tableName     = "নাম"
  tableCountry  = "দেশ"
  tableComment  = "মন্তব্য"
