# == TURKISH ==

# General strings
[Languages.tr]
  languageCode  = "tr"
  languageName  = "Türkçe"
  description   = "Kamusal Para, Kamusal Kod - Kamu tarafından finanse edilmiş yazılımların Özgür Yazılım olarak yayınlanması için bir kampanya"
  fsdefinition  = "Özgür Yazılım herkese yazılımı kullanma, inceleme, paylaşma ve geliştirme hakkını sağlar. Bu hak ifade, basın ve mahremiyet özgürlüğü gibi diğer temel hakları desteklemeye yardımcı olur."


# Navigation
[Languages.tr.navigation]
[Languages.tr.navigation.links]
  start     = "Başlangıç"
  about     = "Hakkında"
  arguments = "Gerekçeler"
  action    = "Harekete Geçin"
  spread    = "Haberi Duyurun"


# Start banner
[Languages.tr.start]
  subtitle1   = "Vergi verenlerin parasıyla üretilen yazılımlar neden Özgür Yazılım olarak yayınlanmıyor?"
  subtitle2   = "Kamu tarafından finanse edilerek kamu sektörü için geliştirilen yazılımların [Özgür ve Açık Kaynak Kodlu Yazılım](https://fossasia.org/freesoftware/basics/summary.html 'Özgür Yazılım herkese yazılımı kullanma, inceleme, paylaşma ve geliştirme hakkını sağlar. Bu hak ifade, basın ve mahremiyet özgürlüğü gibi diğer temel hakları desteklemeye yardımcı olur.') lisansıyla kamuya açık hale getirilmesini sağlayacak mevzuat istiyoruz. Eğer bu kamunun parasıysa o zaman kod da kamusal olmalıdır!"
  subtitle3   = "**Halkın parasıyla üretilen kod, halka açık olmalıdır!**"


# About section
[Languages.tr.about]
  headline    = "Karmaşık mı geldi? Hiç de değil. Oldukça kolay!"
  buttonText  = "Diğer Avantajlar"


# Arguments section
[Languages.tr.arguments]
  headline    = "Kamusal Kod için Gerekçeler"
  followup    = "Kamu tarafından finanse edilen yazılımın standart lisans seçeneğinin Özgür Yazılım olması gerektiğine mi inanıyorsunuz? **O zaman politik temsilcinizi ikna edelim!**"
  buttonText  = "Açık Mektubu İmzalayın"
[[Languages.tr.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Vergi tasarrufu"
  description = "Benzer uygulamalar her seferinde sıfırdan üretilmek zorunda olmayacaktır."
[[Languages.tr.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "İşbirliği"
  description = "Büyük proje çabaları uzmanlığı ve maliyeti paylaşabilir."
[[Languages.tr.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Halka hizmet"
  description = "Kamunun finanse ettiği uygulamalar, herkesin erişimine açık olmalıdır."
[[Languages.tr.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Yenilikçiliği teşvik"
  description = "Şeffaf süreçler sayesinde başkalarının tekerleği yeniden icat etmesi gerekmez."


# Action section
[Languages.tr.action]
  headline      = "Milletvekilinize Söyleyin!"
  intro         = "[**Açık mektubumuzda**](openinitiative/) şunu talep ediyoruz:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“Kamu tarafından finanse edilerek kamu sektörü için geliştirilen yazılımların [Özgür ve Açık Kaynak Kodlu Yazılım](https://fossasia.org/freesoftware/basics/summary.html 'Özgür Yazılım herkese yazılımı kullanma, inceleme, paylaşma ve geliştirme hakkını sağlar. Bu hak ifade, basın ve mahremiyet özgürlüğü gibi diğer temel hakları desteklemeye yardımcı olur.') lisansıyla kamuya açık hale getirilmesini sağlayacak mevzuatı yürürlüğe koyun.”"
  description   = "Şu ana kadar **$ORGS** örgüt ve **$INDS** kişi [açık mektubumuzu](openinitiative/) imzalayarak bu eylem çağrısına desteğini sundu. Siz de imzalayarak daha büyük bir etki yaratmamıza yardımcı olabilirsiniz. Bütün bu imzaları Avrupa çapındaki kamu kurumlarında yazılım özgürlüğünü tartışan milletvekilerine sunacağız."

[Languages.tr.action.box]
  text      = "Şimdiye kadar **$INDS İMZA** – açık mektubu hemen imzalayın!"

[Languages.tr.action.form]
  name          = "Ad-Soyad (gerekli)"
  email         = "E-posta (gerekli)"
  country       = "Ülke"
  region        = "Bölge/şehir"
  organization  = "Organizasyon"
  comment       = "Görüşler (en fazla 140 karakter)"
  permPriv      = "[Gizlilik beyanını](privacy/) okudum ve onaylıyorum"
  permNews      = "Kampanya hakkında haberdar olmak istiyorum"
  permPub       = "Adımın [imzacılar listesinde](openinitiative/all-signatures) gözükmesini istiyorum"
  submit        = "İmzala!"


# Organisations section
[Languages.tr.organisations]
  headline  = "Destekleyen Örgütler"
  text      = "Aşağıdaki örgütler [açık mektubumuzu](openinitiative/) destekliyorlar. Eğer sizin de örgütünüz Kamusal Kod çağrısına katılmakla ilgileniyorsa, lütfen [bizimle bağlantıya geçin](mailto:contact@fossasia.org)."


# Spread the word section
[Languages.tr.spread]
  headline          = "Haberi Duyurun!"
  promoText         = "FSFE'den en güncel çıkartma ve broşürleri sipariş edin"
  promoButtonText   = "Tanıtım malzemesi isteyin"
  shareText         = "Arkadaş ve takipçilerinize Kamusal Kod çağrısını duyurun:"
  defaultSocialText = "Eğer bu kamunun parasıysa o zaman kod da kamusal olmalıdır. Daha fazla kamusal kodun Özgür Yazılım lisansı kapsamına alınması çağrısını destekliyorum:"


# Legal Section
[Languages.tr.legal]
  by            = "Bu Avrupa Özgür Yazılım Vakfı'nın bir kampanyasıdır"
  imprint       = "Yayıncı"
  privacy       = "Gizlilik"
  transparency  = "Şeffaflık"
  contribute1   = "Bu web sitesinin kodu Özgür Yazılımdır."
  contribute2   = "Katkı verebilirsiniz!"
  license       = "Bu çalışma [Creative Commons BY-SA 4.0 Lisansı](http://creativecommons.org/licenses/by-sa/4.0/) kapsamındadır."


# Language selection
[Languages.tr.language]
  description = "Bu sayfayı başka bir dilde okuyun"


# 404 Error Page
[Languages.tr.error]
  headline    = "Error 404 - Sayfa bulunamadı"
  description = "Aradığınız sayfa mevcut değil."
  button      = "Başlangıç sayfasına dönün"


# Specific sub-pages
[Languages.tr.subpage]
[Languages.tr.subpage.signatures]
  headline      = "Bireysel Açık Mektup İmzaları"
  description   = "Aşağıdaki imzalar, isimlerini herkese açık yapmayı kabul edenlerdir. Bir sonraki siz olun!"
  allSignatures = "[Herkese açık imzaları](all-signatures/) görüntüleyin."
  tableName     = "İsim"
  tableCountry  = "Ülke"
  tableComment  = "Görüş"
