# == YOUR LANGUAGE ==

# General strings
[Languages.it]
  languageCode  = "it"
  languageName  = "Italiano"
  description   = "Public Money, Public Code - Una campagna per rilasciare come Software Libero il software finanziato pubblicamente"
  fsdefinition  = "Il Software Libero dà a chiunque il diritto di usare, studiare, condividere e migliorare il software. Questo diritto aiuta a supportare altri diritti fondamentali come la libertà di parola, di stampa e la tutela della privacy."


# Navigation
[Languages.it.navigation]
[Languages.it.navigation.links]
  start     = "Inizio"
  about     = "Informazioni"
  arguments = "Motivazioni"
  action    = "Agisci"
  spread    = "Spargi la voce"


# Start banner
[Languages.it.start]
  subtitle1   = "Perché il software creato usando i soldi delle tasse riscosse dai cittadini non è rilasciato come Software Libero?"
  subtitle2   = "Vogliamo che la legge richieda che il software finanziato pubblicamente e sviluppato per il settore pubblico sia reso pubblicamente disponibile sotto una licenza [Software Libero/Open Source](https://fsfe.org/about/mission.it.html 'Il Software Libero dà a chiunque il diritto di usare, studiare, condividere e migliorare il software. Questo diritto aiuta a supportare altri diritti fondamentali come la libertà di parola, di stampa e la tutela della privacy.') Se è denaro pubblico (public money), allora dovrebbe essere publico anche il codice sorgente (public code)."
  subtitle3   = "**Il codice pagato dalle persone dovrebbe essere disponibile alle persone!**" 


# About section
[Languages.it.about]
  headline    = "Sembra complicato? Non lo è. È super semplice!"
  buttonText  = "Più vantaggi"


# Arguments section
[Languages.it.arguments]
  headline    = "Motivazioni per Public Code"
  followup    = "Credi che il Software Libero dovrebbe essere l'opzione predefinita per il software finanziato pubblicamente? **Convinci i tuoi rappresentanti politici!**"
  buttonText  = "Firma la Lettera Aperta"
[[Languages.it.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Risparmi fiscali"
  description = "Applicazioni simili non dovrebbero essere programmate da zero ogni volta."
[[Languages.it.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "Collaborazione"
  description = "Gli sforzi sui principali progetti possono far condividere competenze e costi."  
[[Languages.it.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Servire il pubblico"
  description = "Le applicazioni pagate dal pubblico dovrebbero essere disponibili a chiunque."
[[Languages.it.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Promozione dell'innovazione"
  description = "Con processi trasparenti, gli altri non devono reinventare la ruota."


# Action section
[Languages.it.action]
  headline      = "Informa i tuoi rappresentanti!"
  intro         = "Nella nostra [**lettera aperta**](openletter/) chiediamo:" 
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“Implementare leggi che richiedano che il software finanziato pubblicamente e sviluppato per il settore pubblico sia reso pubblicamente disponibile sotto una licenza [Software Libero/Open Source](https://fsfe.org/freesoftware/basics/summary.it.html 'Il Software Libero dà a chiunque il diritto di usare, studiare, condividere e migliorare il software. Questo diritto aiuta a supportare altri diritti fondamentali come la libertà di parola, di stampa e la tutela della privacy.').”"
  description   = "**$ORGS** organizzazioni e **$INDS** persone supportano già questa chiamata ad agire attraverso la firma della nostra [lettera aperta](openletter/). Puoi aiutarci ad avere un maggiore impatto firmandola anche tu! Consegneremo tutte le firme ai rappresentanti di tutta Europa che stanno dibattendo sulla libertà del software nelle amministrazioni pubbliche."

[Languages.it.action.box]
  text      = "Già **$INDS SIGNATURES** – firma la lettera aperta adesso!"

[Languages.it.action.form]
  name      = "Nome (required)"
  email     = "Email (required)"
  country   = "La tua nazione"
  zip       = "CAP"
  comment   = "Il tuo commento (max. 140 caratteri)"
  permPriv  = "Ho letto e accettato la [dichiarazione sulla privacy](privacy/)"
  permNews  = "Voglio rimanere informato sull'andamento di questa campagna"
  permPub   = "Voglio che la mia firma compaia nella [lista dei firmatari](openletter/all-signatures)"
  submit    = "Firma ora!"


# Organisations section
[Languages.it.organisations]
  headline  = "Organizzazioni aderenti"
  text      = "Le seguenti organizzazioni supportano la nostra [lettera aperta](openletter/). Se anche la tua organizzazione è interessata ad unirsi alla chiamata per Public Code, per favore [contattaci](mailto:contact@fsfe.org)."


# Spread the word section
[Languages.it.spread]
  headline          = "Spargi la voce!"
  promoText         = "Ordina gli ultimi adesivi e volantini da FSFE"
  promoButtonText   = "Ottieni materiale promozionale"
  shareText         = "Racconta ai tuoi amici e follower di Public Code:"
  defaultSocialText = "Se è denaro pubblico (public money), allora dovrebbe essere pubblico anche il codice sorgente (public code). Supporto questa chiamata per più codice pubblico sotto una licenza di Software Libero: "


# Legal Section
[Languages.it.legal]
  by            = "Questa è una campagna promossa da Free Software Foundation Europe"
  imprint       = "Imprint"
  privacy       = "Privacy"
  transparency  = "Trasparenza"
  contribute1   = "Il codice di questo sito web è Software Libero." 
  contribute2   = "Se vuoi contribuire sei il benvenuto!"
  license       = "Questo lavoro è licenziato sotto la [licenza Creative Commons BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/)."


# Language selection
[Languages.it.language]
  description = "Leggi questa pagina in un'altra lingua"


# 404 Error Page
[Languages.it.error]
  headline    = "Errore 404 - Pagina non trovata"
  description = "La pagina che stavi cercando non esiste."
  button      = "Torna alla pagina iniziale"


# Specific sub-pages
[Languages.it.subpage]
[Languages.it.subpage.signatures]
  headline      = "Firmatari individuali della Lettera Aperta"
  description   = "Sotto ci sono le firme dei firmatari che hanno acconsentito alla pubblicazione del loro nome. Sii il prossimo!"
  allSignatures = "Guarda [tutte le firme pubbliche](all-signatures/)."
  tableName     = "Nome"
  tableCountry  = "Nazione"
  tableComment  = "Commento"
