# == GREEK ==

# General strings
[Languages.el]
  languageCode  = "el"
  languageName  = "Ελληνικά"
  description   = "Δημόσιο χρήμα, Δημόσιος κώδικας - Μια καμπάνια για την διανομή δημόσια χρηματοδοτούμενο λογισμικού ως Ελεύθερο Λογισμικό"
  fsdefinition  = "Το Ελεύθερο Λογισμικό δίνει σε όλους το δικαίωμα να χρησιμοποιούν, να μελετούν, να μοιράζονται και να βελτιώνουν το λογισμικό. Αυτό το δικαίωμα βοηθά στην υποστήριξη άλλων θεμελιωδών ελευθεριών όπως η ελευθερία του λόγου, του τύπου και της ιδιωτικότητας."


# Navigation
[Languages.el.navigation]
[Languages.el.navigation.links]
  start     = "Αρχική"
  about     = "Σχετικά"
  arguments = "Λόγοι"
  action    = "Ανέλαβε Δράση"
  spread    = "Διάδωσε το"


# Start banner
[Languages.el.start]
  subtitle1   = "Γιατί το λογισμικό που δημιουργείται με χρήματα φορολογουμένων πολιτών δεν διανέμεται ως Ελεύθερο Λογισμικό;"
  subtitle2   = "Θέλουμε νομοθεσία που να απαιτεί ότι το δημόσια χρηματοδοτούμενο λογισμικό που αναπτύσσεται για το δημόσιο τομέα πρέπει να διατίθεται δημοσίως με άδεια χρήσης [ελεύθερου και ανοιχτού λογισμικού](https://fsfe.org/about/mission.html 'Το Ελεύθερο Λογισμικό δίνει σε όλους το δικαίωμα να χρησιμοποιούν, να μελετούν, να μοιράζονται και να βελτιώνουν το λογισμικό. Αυτό το δικαίωμα βοηθά στην υποστήριξη άλλων θεμελιωδών ελευθεριών όπως η ελευθερία του λόγου, του τύπου και της ιδιωτικότητας.'). Αν είναι δημόσιο χρήμα, θα έπρεπε να είναι και δημόσιος κώδικας."
  subtitle3   = "**Κώδικας που πληρώνεται από τους πολίτες πρέπει να είναι διαθέσιμος και στους πολίτες!**"


# About section
[Languages.el.about]
  headline    = "Ακούγεται περίπλοκο; Δεν είναι. Είναι πολύ απλό!"
  buttonText  = "Περισσότερα πλεονεκτήματα"


# Arguments section
[Languages.el.arguments]
  headline    = "Λόγοι για Δημόσιο Κώδικα"
  followup    = "Πιστεύεις πως το Ελεύθερο Λογισμικό θα έπρεπε να είναι η πρωταρχική επιλογή για δημόσια χρηματοδοτούμενο λογισμικό; **Ας πείσουμε τους πολιτικούς μας αντιπροσώπους!**"
  buttonText  = "Υπόγραψε την Ανοιχτή Επιστολή"
[[Languages.el.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Εξοικονόμηση φόρων"
  description = "Παρόμοιες εφαρμογές δεν χρειάζεται να προγραμματιστούν απ' το μηδέν κάθε φορά."
[[Languages.el.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "Συνεργασία"
  description = "Πρωτοβουλίες σε μεγάλα έργα μπορούν μοιραστούν τεχνογνωσία και κόστος."
[[Languages.el.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Υπηρετώντας τους πολίτες"
  description = "Οι εφαρμογές που πληρώθηκαν απ' τους πολίτες θα έπρεπε να είναι διαθέσιμες σε όλους."
[[Languages.el.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Καινοτομία"
  description = "Με διαφανείς διαδικασίες, δεν χρειάζεται να ανακαλύπτουμε συνεχώς τον τροχό."


# Action section
[Languages.el.action]
  headline      = "Πες το στους αντιπροσώπούς σου!"
  intro         = "Στην [**ανοιχτή επιστολή**](openletter/) μας απαιτούμε:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“Υλοποίηση νομοθεσίας που να απαιτεί ότι το δημόσια χρηματοδοτούμενο λογισμικό που αναπτύσσεται για το δημόσιο τομέα πρέπει να διατίθεται δημοσίως με άδεια χρήσης [ελεύθερου και ανοιχτού λογισμικού](https://fsfe.org/freesoftware/basics/summary.html 'Το Ελεύθερο Λογισμικό δίνει σε όλους το δικαίωμα να χρησιμοποιούν, να μελετούν, να μοιράζονται και να βελτιώνουν το λογισμικό. Αυτό το δικαίωμα βοηθά στην υποστήριξη άλλων θεμελιωδών ελευθεριών όπως η ελευθερία του λόγου, του τύπου και της ιδιωτικότητας.').”"
  description   = "**$ORGS** οργανισμοί και **$INDS** άνθρωποι έχουν ήδη υποστηρίξει αυτό το κάλεσμα για δράση υπογράφοντας [ανοιχτή επιστολή](openletter/) μας. Μπορείς να μας βοηθήσεις υπογράφοντας τη και ενισχύοντας το μήνυμα μας! Θα παραδώσουμε όλες τις υπογραφές σε αντιπροσώπους σε όλη την Ευρώπη που αμφισβητούν το ελεύθερο λογισμικό στη δημόσια διοίκηση."

[Languages.el.action.box]
  text      = "Ήδη **$INDS ΥΠΟΓΡΑΦΕΣ** – υπόγραψε την ανοιχτή επιστολή τώρα!"

[Languages.el.action.form]
  name      = "Όνομα (απαραίτητο)"
  email     = "Email (απαραίτητο)"
  country   = "Χώρα"
  zip       = "ΤΚ"
  comment   = "Το σχόλιο σου (μεγ. 140 χαρακτήρες)"
  permPriv  = "Έχω διαβάσει και αποδεχτεί την [πολιτική ιδιωτικότητας](privacy/)"
  permNews  = "Επιθυμώ να ενημερώνομαι για το μέλλον αυτής της καμπάνιας"
  permPub   = "Επιθυμώ η υπογραφή μου να εμφανιστεί στη [λίστα υπογραφών](openletter/all-signatures)"
  submit    = "Υπόγραψε Τώρα!"


# Organisations section
[Languages.el.organisations]
  headline  = "Οργανισμοί που υποστηρίζουν"
  text      = "Οι παρακάτω οργανισμοί υποστηρίζουν την [ανοιχτή επιστολή](openletter/) μας. Αν ο οργανισμός σου ενδιαφέρεται επίσης να συμμετάσχει στο κάλεσμα για Δημόσιο Κώδικα, παρακαλώ [επικοινωνήστε μαζί μας](mailto:contact@fsfe.org)."


# Spread the word section
[Languages.el.spread]
  headline          = "Διάδωσε το!"
  promoText         = "Παράγγειλε τα πρόσφατα αυτοκόλλητα και φυλλάδια από το FSFE"
  promoButtonText   = "Ζήτησε προωθητικό υλικό"
  shareText         = "Μίλησε στους φίλους/ες και στις επαφές σου για τον Δημόσιο Κώδικα:"
  defaultSocialText = "Αν είναι δημόσιο χρήμα, θα έπρεπε να είναι δημόσιος κι ο κώδικας. Υποστηρίζω αυτό το κάλεσμα για περισσότερο δημόσιο κώδικα με μια άδεια Ελεύθερου Λογισμικού:"


# Legal Section
[Languages.el.legal]
  by            = "Αυτή είναι μια καμπάνια απ' το Free Software Foundation Europe"
  imprint       = "Νομικά Στοιχεία"
  privacy       = "Πολιτική Ιδιωτικότητας"
  transparency  = "Δέσμευση Διαφάνειας"
  contribute1   = "Ο κώδικας αυτού site είναι Ελεύθερο Λογισμικό."
  contribute2   = "Είσαι ευπρόσδεκτος/η να συνεισφέρεις!"
  license       = "Αυτό το έργο διανέμεται με άδεια [Creative Commons BY-SA 4.0 Licence](http://creativecommons.org/licenses/by-sa/4.0/)."


# Language selection
[Languages.el.language]
  description = "Διάβασε αυτή τη σελίδα σε άλλη γλώσσα"


# 404 Error Page
[Languages.el.error]
  headline    = "Λάθος 404 - Αυτή η σελίδα δεν βρέθηκε"
  description = "Η σελίδα που ψάχνεις δεν υπάρχει."
  button      = "Πίσω στην αρχική σελίδα"


# Specific sub-pages
[Languages.el.subpage]
[Languages.el.subpage.signatures]
  headline      = "Υπογραφές στην Ανοιχτή Επιστολή"
  description   = "Παρακάτω είναι οι υπογραφές όσων συμφώνησαν να είναι δημόσια τα ονόματα τους. Γίνε ο επόμενος/η!"
  allSignatures = "Δες [όλες τις δημόσιες υπογραφές](all-signatures/)."
  tableName     = "Όνομα"
  tableCountry  = "Χώρα"
  tableComment  = "Σχόλιο"
