# == GERMAN ==

# General strings
[Languages.de]
  languageCode  = "de"
  languageName  = "Deutsch"
  description   = "Public Money, Public Code - Eine Kampagne, damit öffentlich finanzierte Software als Freie Software veröffentlicht wird"
  fsdefinition  = "Freie Software gibt allen das Recht, Programme für jeden Zweck zu verwenden, zu verstehen, zu verbreiten und zu verbessern. Diese Freiheiten stärken andere Grundrechte wie die Redefreiheit, die Pressefreiheit und das Recht auf Privatsphäre."


# Navigation
[Languages.de.navigation]
[Languages.de.navigation.links]
  start     = "Start"
  about     = "Über"
  arguments = "Argumente"
  action    = "Werde aktiv"
  spread    = "Weitersagen"


# Start banner
[Languages.de.start]
  subtitle1  = "Warum wird durch Steuergelder finanzierte Software nicht als Freie Software veröffentlicht?"
  subtitle2  = "Wir wollen rechtliche Grundlagen, die es erfordern, dass mit öffentlichen Geldern für öffentliche Verwaltungen entwickelte Software unter einer [Freie-Software- und Open-Source Lizenz](https://fsfe.org/freesoftware/basics/summary.html 'Freie Software gibt allen das Recht, Programme für jeden Zweck zu verwenden, zu verstehen, zu verbreiten und zu verbessern. Diese Freiheiten stärken andere Grundrechte wie die Redefreiheit, die Pressefreiheit und das Recht auf Privatsphäre.') veröffentlicht wird. Wenn es sich um öffentliche Gelder handelt, sollte auch der Code öffentlich sein!"
  subtitle3  = "**Von allen bezahlter Code sollte für alle verfügbar sein!**"


# About section
[Languages.de.about]
  headline    = "Klingt kompliziert? Nein, es ist super einfach!"
  buttonText  = "Weitere Vorteile"


# Arguments section
[Languages.de.arguments]
  headline    = "Gründe für Public Code"
  followup    = "Glaubst du, dass Freie Software die Standardoption für öffentlich finanzierte Software sein sollte? **Dann lass uns deine Abgeordneten überzeugen!**"
  buttonText  = "Den Offenen Brief unterzeichnen"
[[Languages.de.arguments.list]]
  icon        = "fa-eur"  # <-- do not translate this
  title       = "Steuereinsparungen"
  description = "Ähnliche Programme müssen nicht komplett neu programmiert werden."
[[Languages.de.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "Zusammenarbeit"
  description = "Bei großen Projekten können Expertise und Kosten geteilt werden."
[[Languages.de.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "Allgemeinwohl"
  description = "Von der Allgemeinheit bezahlte Anwendungen sollten allen zur Verfügung stehen."
[[Languages.de.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "Innovationen fördern"
  description = "Dank transparenter Prozesse müssen andere nicht das Rad neu erfinden."


# Action section
[Languages.de.action]
  headline      = "Sag es deinen Abgeordneten!"
  intro         = "In unserem [**Offenen Brief**](openinitiative/) fordern wir:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "„Wir brauchen rechtliche Grundlagen, die es erfordern, dass mit öffentlichen Geldern für öffentliche Verwaltungen entwickelte Software unter einer [Freie-Software- und Open-Source Lizenz](https://fsfe.org/freesoftware/basics/summary.html 'Freie Software gibt allen das Recht, Programme für jeden Zweck zu verwenden, zu verstehen, zu verbreiten und zu verbessern. Diese Freiheiten stärken andere Grundrechte wie die Redefreiheit, die Pressefreiheit und das Recht auf Privatsphäre.') veröffentlicht wird.“"
  description   = "**$ORGS** Organisationen und **$INDS** Personen unterstützen bereits diesen Aufruf, indem sie unseren [Offenen Brief](openinitiative/) unterzeichnet haben. Du kannst uns helfen, einen viel größeren Einfluss auszuüben, indem auch du ihn unterzeichnest! Wir werden alle Unterschriften an Abgeordnete in ganz Europa, die Softwarefreiheit in öffentlichen Verwaltungen erörtern, überreichen."

[Languages.de.action.box]
  text      = "Schon **$INDS UNTERSCHRIFTEN** – jetzt den offenen Brief unterzeichnen!"

[Languages.de.action.form]
  name          = "Name (Pflichtfeld)"
  email         = "E-Mail (Pflichtfeld)"
  country       = "Dein Land"
  region        = "Region/Stadt"
  organization  = "Organisation"
  comment       = "Dein Kommentar (max. 140 Zeichen)"
  permPriv      = "Ich habe die [Datenschutzerklärung](privacy/) gelesen und akzeptiere sie"
  permNews      = "Ich möchte über den Verlauf der Kampagne informiert werden"
  permPub       = "Meine Unterschrift in der [Unterschriftenliste](openinitiative/all-signatures) anzeigen"
  submit        = "Jetzt unterzeichnen!"


# Organisations section
[Languages.de.organisations]
  headline  = "Unterstützende Organisationen"
  text      = "Die folgenden Organisationen unterstützen unseren [Offenen Brief](openinitiative/). Wenn deine Organisation sich ebenfalls dem Aufruf für Public Code anschließen will, [kontaktiere uns bitte](mailto:contact@fsfe.org)."


# Spread the word section
[Languages.de.spread]
  headline          = "Weitersagen!"
  promoText         = "Die neuesten Sticker und Flyer der FSFE bestellen"
  promoButtonText   = "Infomaterial erhalten"
  shareText         = "Erzähle deinen Freunden und Followern von Public Code:"
  defaultSocialText = "Öffentliches Geld? Öffentlicher Code! Ich unterstütze den Aufruf zu mehr öffentlichem Code unter einer Freie-Software-Lizenz:"


# Legal Section
[Languages.de.legal]
  by            = "Eine Kampagne der Free Software Foundation Europe"
  imprint       = "Impressum"
  privacy       = "Datenschutz"
  transparency  = "Transparenz"
  contribute1   = "Der Code dieser Website ist Freie Software."
  contribute2   = "Du kannst dazu beitragen, sie zu verbessern."
  license       = "Diese Seite ist lizensiert unter einer [Creative Commons BY-SA 4.0 License](http://creativecommons.org/licenses/by-sa/4.0/)-Lizenz."


# Language selection
[Languages.de.language]
  description = "Diese Seite in einer anderen Sprache lesen"


# 404 Error Page
[Languages.de.error]
  headline    = "Fehler 404 - Seite nicht gefunden"
  description = "Diese Seite existiert nicht."
  button      = "Zurück zur Startseite"


# Specific sub-pages
[Languages.de.subpage]
[Languages.de.subpage.signatures]
  headline      = "Übersicht der Unterschriften"
  description   = "Hier sind die Unterschriften von allen Unterzeichnern, die damit einverstanden waren, ihren Namen zu veröffentlichen. Sei der Nächste!"
  allSignatures = "[Alle öffentlichen Unterschriften ansehen](all-signatures/)."
  tableName     = "Name"
  tableCountry  = "Land"
  tableComment  = "Kommentar"
